# -*- coding: utf-8 -*-
"""VTCA-COTAI-Getting started

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MtHlbO9yrn8iQT54A_rzIHDqWTK9KYYh
"""

# Sample code: Drawing multiple points on a 2D graph
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

horizontal_values = [1, 4, 9, 16, 25]
vertical_values = [1, 2, 3, 4, 5]

plt.scatter(horizontal_values, vertical_values, s=10, c="blue")
plt.show()

# Sample code: Drawing multiple lines (represent a function) on a 2D graph
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

horizontal_values = [0, 1, 2, 3, 4, 5]
vertical_values = [0, 1, 4, 9, 16, 25]

plt.plot(horizontal_values, vertical_values, linewidth=3, color="blue")
plt.show()

import numpy as np

# Generate 50 evenly spaced numbers over a specified interval [2.0, 10.0]
np.linspace(2.0, 10.0, num=50)

import numpy as np

# Generate random matrix M size 10*3 (10 rows, 3 columns)
M = np.random.rand(10, 3)
print(M)

# Get all numbers in column index 1:
column1 = M[:, 1]
print(column1)

"""https://www.w3schools.com/python is a good place to learn python. For this course, you should focus on belows lessions first:

- Getting Started: https://www.w3schools.com/python/python_getstarted.asp
- Basic syntax:
https://www.w3schools.com/python/python_syntax.asp
- Comments:
https://www.w3schools.com/python/python_comments.asp
- Variables: https://www.w3schools.com/python/python_variables.asp
- Data types: https://www.w3schools.com/python/python_datatypes.asp
- Numbers: https://www.w3schools.com/python/python_numbers.asp
- Casting: https://www.w3schools.com/python/python_casting.asp
- Strings: https://www.w3schools.com/python/python_strings.asp
- Booleans: https://www.w3schools.com/python/python_booleans.asp
- Operators (toán tử): https://www.w3schools.com/python/python_operators.asp
- Lists: https://www.w3schools.com/python/python_lists.asp
- Tuples: https://www.w3schools.com/python/python_tuples.asp
- Sets: https://www.w3schools.com/python/python_sets.asp
- Dictionaries: https://www.w3schools.com/python/python_dictionaries.asp
- If ... else: https://www.w3schools.com/python/python_conditions.asp
- While: https://www.w3schools.com/python/python_while_loops.asp
- For: https://www.w3schools.com/python/python_for_loops.asp
- Functions: https://www.w3schools.com/python/python_functions.asp
- Arrays: https://www.w3schools.com/python/python_arrays.asp
- Iterators: https://www.w3schools.com/python/python_iterators.asp

Note: `Arrays` in python is difference from `numpy array`

More about numpy array, please read at: https://numpy.org/doc/1.17/user/quickstart.html. For quickly beginning, you can read this: https://www.guru99.com/numpy-tutorial.html
"""
