# -*- coding: utf-8 -*-
"""VTCA-COTAI-FunctionSpace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TuYWJx8dxiMnyZx-EuVNEakLhNLBcOXj

<img height="45px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF7hEhixicjCwPYaFpS-HHTbnDNr_do_z0ov6Qf29RjuJ2y0TD" align="left" hspace="10px" vspace="0px">

<h1>VTCA - COTAI - Function space</h1>

Draw animation in page 4-5 of lecture 2
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

from matplotlib import animation, rc

# ==============================================================================
# Defines convenient functioins
# ==============================================================================

def formatCoordinateSpines(ax):
  ax.spines['right'].set_color('none')
  ax.spines['top'].set_color('none')
  ax.xaxis.set_ticks_position('bottom')
  ax.spines['bottom'].set_position(('data', 0))
  ax.yaxis.set_ticks_position('left')
  ax.spines['left'].set_position(('data', 0))


def formatCoordinateLimit(ax, x_range, y_range):
  ax.set_xlim(x_range[0], x_range[1])
  ax.set_ylim(x_range[0], x_range[1])
  ax.set_xticks(np.linspace(
      x_range[0],
      x_range[1],
      -x_range[0]+x_range[1]+1,
      endpoint=True
  ))
  ax.set_yticks(np.linspace(
      y_range[0],
      y_range[1],
      -y_range[0]+y_range[1]+1,
      endpoint=True
  ))


def drawGraphOfASingleFunction(ax, x_range, funcObj, color="red", linewidth=1.0, linestyle="-"):
  X = np.linspace(x_range[0], x_range[1], 256, endpoint=True)
  Y = funcObj.calculateY(X)
  ax.plot(X, Y, color, linewidth, linestyle)


def drawContourInFunctionSpace(ax, x_range, y_range, funcObj):
  sampleX = np.linspace(x_range[0], x_range[1], 256, endpoint=True)
  sampleY = np.linspace(y_range[0], y_range[1], 256, endpoint=True)
  A, B = np.meshgrid(sampleX, sampleY)
  Z = funcObj.calculateContourLevel(A, B)
  CS = axContour.contour(A, B, Z, cmap=cm.rainbow)
  ax.clabel(CS, inline=1, fontsize=10)


def drawDot(ax, horizontal, vertical, style):
  ax.plot([horizontal], [vertical], style)

# ==============================================================================
# End of utilities functions
# ==============================================================================


class LinearFunc:
  # this allow you to define a function object with 2 required methods:
  # - calculateY
  # - calculateContourLevel
  # These 2 methods will be invoked by functions: drawGraphOfASingleFunction, drawContourInFunctionSpace
  def __init__(self, A=None, X=None, B=None):
    self.X = X
    self.A = A
    self.B = B

  # yes, you define your own linear function f(x) right here
  def __equation(self, A, X, B):
    return A*X+B
  
  # Value of A, B are fixxed while calculating values of Y by X
  # Value of X is sampled by function np.linspace before
  def calculateY(self, X):
    return self.__equation(self.A, X, self.B)

  # Value of X is fixxed while calculating countour level.
  # Value of A, B are sampled by function np.linspace before
  def calculateContourLevel(self, A, B):
    return self.__equation(A, self.X, B)


x_range = [-2, 2]
y_range = [-2, 2]
a_range = [-2, 2]
b_range = [-2, 2]

# Create a figure of size 8x6 inches, 80 dots per inch
fig = plt.figure(figsize=(12, 6), dpi=80)
plt.close()

axContour = fig.add_subplot(1, 2, 1)
axGraph = fig.add_subplot(1, 2, 2)

formatCoordinateSpines(axGraph)
formatCoordinateSpines(axContour)
formatCoordinateLimit(axGraph, x_range, y_range)
formatCoordinateLimit(axContour, a_range, b_range)


def animationInit():
  drawContourInFunctionSpace(axContour, x_range, y_range, LinearFunc(X=1))
  return ()


def animate(i):
  A = 2-i/4
  B = -A+1
  drawDot(axContour, A, B, "go")
  drawGraphOfASingleFunction(axGraph, x_range, LinearFunc(A=A, B=B), color="green")
  return ()


anim = animation.FuncAnimation(
    fig=fig, func=animate, init_func=animationInit, 
    frames=100, interval=100, blit=True)
rc('animation', html='jshtml')
anim

# replace anim by below code to save animation to file .mp4
# anim.save('animation.mp4')

x_range = [-2, 2]
y_range = [-2, 2]
a_range = [-2, 2]
b_range = [-2, 2]
    
# Create a figure of size 8x6 inches, 80 dots per inch
fig = plt.figure(figsize=(12, 6), dpi=80)
plt.close()

axContour = fig.add_subplot(1, 2, 1)
axGraph = fig.add_subplot(1, 2, 2)

formatCoordinateSpines(axGraph)
formatCoordinateSpines(axContour)
formatCoordinateLimit(axContour, a_range, b_range)
formatCoordinateLimit(axGraph, x_range, y_range)


def animationInit():
  drawContourInFunctionSpace(axContour, x_range, y_range, LinearFunc(X=1))  
  return ()

def animate(i):
  B = -2 + i/4
  A = B**2/2-1

  drawDot(axContour, A, B, "bo")
  drawGraphOfASingleFunction(axGraph, x_range,  LinearFunc(A=A,B=B), color="blue")
  return ()
  
anim = animation.FuncAnimation(fig=fig, func=animate, init_func=animationInit, frames=18, interval=100, blit=True)
rc('animation', html='jshtml')
anim

# replace anim by below code to save animation to file .mp4
# anim.save('animation.mp4')

class SigmoidFunc:
  def __init__(self,A=None,X=None,B=None):
    self.X = X
    self.A = A
    self.B = B
  
  def __equation(self, A,X,B):
    return np.tanh(A*X+B)
    
  def calculateY(self, X):
    return self.__equation(self.A, X, self.B)
  
  def calculateContourLevel(self, A,B):
    return self.__equation(A,self.X,B)

x_range = [-2, 2]
y_range = [-2, 2]
a_range = [-2, 2]
b_range = [-2, 2]
    
# Create a figure of size 8x6 inches, 80 dots per inch
fig = plt.figure(figsize=(12, 6), dpi=80)
plt.close()

axContour = fig.add_subplot(1, 2, 1)
axGraph = fig.add_subplot(1, 2, 2)

formatCoordinateSpines(axGraph)
formatCoordinateSpines(axContour)
formatCoordinateLimit(axGraph, x_range, y_range)
formatCoordinateLimit(axContour, a_range, b_range)


def animationInit():
  drawContourInFunctionSpace(axContour, x_range, y_range, SigmoidFunc(X=1))  
  return ()

def animate(i):
  A = 2-i/4
  B = -A-0.25
  drawDot(axContour, A, B, "go")
  drawGraphOfASingleFunction(axGraph, x_range, SigmoidFunc(A=A,B=B), color="green")
  return ()
  
anim = animation.FuncAnimation(fig=fig, func=animate, init_func=animationInit, frames=18, interval=100, blit=True)
rc('animation', html='jshtml')
anim

# replace anim by below code to save animation to file .mp4
# anim.save('animation.mp4')

x_range = [-2, 2]
y_range = [-2, 2]
a_range = [-2, 2]
b_range = [-2, 2]
    
# Create a figure of size 8x6 inches, 80 dots per inch
fig = plt.figure(figsize=(12, 6), dpi=80)
plt.close()

axContour = fig.add_subplot(1, 2, 1)
axGraph = fig.add_subplot(1, 2, 2)

formatCoordinateSpines(axGraph)
formatCoordinateSpines(axContour)
formatCoordinateLimit(axGraph, x_range, y_range)
formatCoordinateLimit(axContour, x_range, y_range)


def animationInit():
  drawContourInFunctionSpace(axContour, x_range, y_range, SigmoidFunc(X=1))  
  return ()

def animate(i):
  B = -2 + i/4
  A = B**2/2-1
  drawDot(axContour, A, B, "bo")
  drawGraphOfASingleFunction(axGraph, x_range, SigmoidFunc(A=A,B=B), color="blue")
  return ()
  
anim = animation.FuncAnimation(fig=fig, func=animate, init_func=animationInit, frames=18, interval=100, blit=True)
rc('animation', html='jshtml')
anim

# replace anim by below code to save animation to file .mp4
# anim.save('animation.mp4')

# ====================================================
# |         Example code without class               |
# ====================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

from matplotlib import animation, rc

# Create a figure of size 8x6 inches, 80 dots per inch
fig = plt.figure(figsize=(12, 6), dpi=80)
plt.close()

axContour = fig.add_subplot(1, 2, 1)
axGraph = fig.add_subplot(1, 2, 2)

# Format coordinate spines of axGraph
axGraph.spines['right'].set_color('none')
axGraph.spines['top'].set_color('none')
axGraph.xaxis.set_ticks_position('bottom')
axGraph.spines['bottom'].set_position(('data', 0))
axGraph.yaxis.set_ticks_position('left')
axGraph.spines['left'].set_position(('data', 0))

# Config limit and ticks on each axis of axGraph
axGraph.set_xlim(-2, 2)
axGraph.set_ylim(-2, 2)
axGraph.set_xticks(np.linspace(-2,2,5,endpoint=True))
axGraph.set_yticks(np.linspace(-2,2,5,endpoint=True))

# Format coordinate spines of axGraph
axContour.spines['right'].set_color('none')
axContour.spines['top'].set_color('none')
axContour.xaxis.set_ticks_position('bottom')
axContour.spines['bottom'].set_position(('data', 0))
axContour.yaxis.set_ticks_position('left')
axContour.spines['left'].set_position(('data', 0))

# Config limit and ticks on each axis of axContour
axContour.set_xlim(-2, 2)
axContour.set_ylim(-2, 2)
axContour.set_xticks(np.linspace(-2,2,5,endpoint=True))
axContour.set_yticks(np.linspace(-2,2,5,endpoint=True))


def animate(i):
  # Each function is determined by a pair of a,b.
  # Generate a pair of a,b with given i
  a = 2-i/4
  b = -a+1

  # draw a single dot in axContour corresponding to 
  # generated pair of a,b
  axContour.plot([a], [b], 'go')

  # draw a corresponding graph of the 
  # function (determined by above pair a,b) in axGraph.
  # First, generage sample value of x
  # Second, calculate values of y corresponding values of x
  X = np.linspace(-2, 2, 256, endpoint=True)
  Y = a*X+b

  # Draw
  axGraph.plot(X, Y, color='green', linewidth=1.0, linestyle='-')
  return ()


def animationInit():
  # Generate sample of x, y in each corresponding range
  sampleX = np.linspace(-2, 2, 256, endpoint=True)
  sampleY = np.linspace(-2, 2, 256, endpoint=True)
  
  # using function np.meshgrid to generate samples of a, b
  A, B = np.meshgrid(sampleX, sampleY)

  # We wanna draw contour corresponding to x=1
  # on axContour. Well, let's assign
  # x=1 and calculate contour level - called z
  x = 1
  Z = A*x + B

  
  # using method contour of axContour to draw our contours
  CS = axContour.contour(A, B, Z, cmap=cm.rainbow)
  axContour.clabel(CS, inline=1, fontsize=10)
  return ()


# Let's generate an animation
anim = animation.FuncAnimation(
    fig=fig, 
    func=animate, 
    init_func=animationInit, 
    frames=18, 
    interval=100, 
    blit=True
)
rc('animation', html='jshtml')
anim

# replace anim by below code to save animation to file .mp4
# anim.save('animation.mp4')

